apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: architecture-sts
spec:
  selector:
    matchLabels:
      app: architecture
  serviceName: architecture
  replicas: 2
  template:
    metadata:
      labels:
        app: architecture
    spec:
      containers:
      - name: architecture
        image: maciejgum/arch:latest
        ports:
        - containerPort: 8080
          name: http
        env:
          - name: POD_IP
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
        envFrom:
          - configMapRef:
              name: architecture-env
        volumeMounts:
        - name: rocksdb
          mountPath: /usr/rocksdb
        
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 50
          periodSeconds: 15

        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 50
          periodSeconds: 15

#      affinity:
#        podAntiAffinity:
#          requiredDuringSchedulingIgnoredDuringExecution:
#            - labelSelector:
#                matchExpressions:
#                  - key: app
#                    operator: In
#                    values:
#                      - "orders-view-app"
#              topologyKey: "kubernetes.io/hostname"
          
  volumeClaimTemplates:
  - metadata:
      name: rocksdb
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi
